2025-01-09 18:44:51,844 - ERROR - ❌ Ошибка в контексте 'Focus Tracker Update Error': [Errno 2] No such file or directory: 'core/data/focus_tracker.json'
2025-01-09 18:44:52,919 - ERROR - ❌ Ошибка в контексте 'Script Execution Error': Ошибка при выполнении скрипта generate_content: Command '['python', 'C:\\Users\\boyar\\core\\scripts\\generate_content.py']' returned non-zero exit status 1.
2025-01-30 01:29:24,252 - ERROR - ❌ Ошибка в контексте '<Logger b2_storage_manager (INFO)>': Main Process Error: name 'CONFIG_GEN_PATH' is not defined
2025-01-30 02:18:05,803 - ERROR - ❌ Ошибка в контексте '<Logger b2_storage_manager (INFO)>': Main Process Error: name 'download_file_from_b2' is not defined
